
variables:
  DOMAIN: schema.example.com

test:
  image: quay.io/podman/stable:latest
  stage: .pre
  script:
  - |
    yum install -y openssl
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    openssl req -x509 -newkey rsa:4096 -keyout server.key -out server.crt -sha256 -days 3650 -nodes -subj "/CN=${DOMAIN}" -addext "subjectAltName=DNS:${DOMAIN},DNS:localhost,IP:127.0.0.1"
    cp server.crt /etc/pki/ca-trust/source/anchors/server.crt
    update-ca-trust
    podman build -t test .
    podman run -d --name test -p 443:443 test
    echo "127.0.0.1 ${DOMAIN}" >> /etc/hosts
    helm lint schema-test/

pages:
  needs: ["test"]
  script:
  - |
    echo "Publish schemas for ${DOMAIN}"
    for file in $(find public/ -maxdepth 3 -regextype posix-extended -iregex '.*[.]json' | sort -g); do 
      cat $file | envsubst "$(env | sed -e 's/=.*//' -e 's/^/\$/g')" > $file
      echo "Modified: $file"
    done
  artifacts:
    paths:
      - public