{{- define "common.tpl.container" -}}
{{- $defaultValues := dict 
    "livenessProbe" ( dict 
        "enabled" true
        "initialDelaySeconds" 5
        "periodSeconds" 10
    )
    "readinessProbe" ( dict
        "enabled" true 
        "initialDelaySeconds" 5
        "periodSeconds" 5
    )
    "startupProbe" ( dict
        "enabled" true 
        "initialDelaySeconds" 5
        "periodSeconds" 10
    )
-}}
{{- $_ := set . "Values" (merge .Values $defaultValues ) }}
{{- if .Values.livenessProbe.enabled }}
livenessProbe:
  {{- if .Values.livenessProbe.command }}
  exec:
    command:
      - {{ .Values.livenessProbe.command }}
  {{- else }}
  httpGet:
    path: {{ .Values.livenessProbe.path }}
    port: {{ .Values.livenessProbe.port }}
  {{- end }}
  initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
  periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
{{- end }}
{{- if .Values.readinessProbe.enabled }}
readinessProbe:
  {{- if .Values.readinessProbe.command }}
  exec:
    command:
      - {{ .Values.readinessProbe.command }}
  {{- else }}
  httpGet:
    path: {{ .Values.readinessProbe.path }}
    port: {{ .Values.readinessProbe.port }}
  {{- end }}
  initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
  periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
{{- end }}
{{- if .Values.startupProbe.enabled }}
startupProbe:
  {{- if .Values.startupProbe.command }}
  exec:
    command:
      - {{ .Values.startupProbe.command }}
  {{- else }}
  httpGet:
    path: {{ .Values.startupProbe.path }}
    port: {{ .Values.startupProbe.port }}
  {{- end }}
  failureThreshold: {{ .Values.startupProbe.failureThreshold }}
  periodSeconds: {{ .Values.startupProbe.periodSeconds }}
{{- end }}
securityContext:
  {{- toYaml .Values.securityContext | nindent 2 }}
image: {{ include "common.images.image" ( dict "imageRoot" .Values.image "global" .Values.global ) }}
imagePullPolicy: {{ .Values.image.pullPolicy }}
resources:
  {{- toYaml .Values.resources | nindent 2 }}

{{- end -}}