{{- define "common.tpl.serviceaccount" -}}
{{- $defaultValues := dict
    "enabled" true
-}}
{{- $_ := set .Values "serviceaccount" (merge .Values.serviceaccount $defaultValues ) }}
{{- if .Values.serviceaccount.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  {{- with .Values.serviceaccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}